# apiVersion: skaffold/v4beta1
# kind: Config
# build:
#   googleCloudBuild:
#     projectId: ticketing-dev-385109
#   artifacts:
#     - image: tianboalbert/auth
#       context: auth
#       sync:
#         manual:
#           - src: src/**/*.ts
#             dest: .
#       docker:
#         dockerfile: Dockerfile
#   local:
#     push: false
# manifests:
#   rawYaml:
#     - ./infra/k8s/*

apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-385109
  artifacts:
    - image: tianboalbert/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: tianboalbert/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: tianboalbert/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: tianboalbert/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: tianboalbert/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: tianboalbert/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
