name: deploy-auth

on: 
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
#     检查repo中的所有代码
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t tianboalbert/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push tianboalbert/auth
      
